const constants = {
   	ADD_DESIDERATA: "ADD_DESIDERATA", 
    REMOVE_DESIDERATA: "REMOVE_DESIDERATA",
    UPDATE_DESIDERATA:"UPDATE_DESIDERATA",
    INIT_DESIDERATAS:"INIT_DESIDERATAS"
}

export default constants